openapi: 3.2.0
info:
  title: Conduit Nodes Pepu V2 Mainnet 0 API
  version: 1.0.0
tags:
- name: Pepu V2 Mainnet 0
paths:
  /pepu-v2-mainnet-0/:
    post:
      responses:
        '200':
          description: Successful response
      tags:
      - Pepu V2 Mainnet 0
      summary: Create pepu v2 mainnet 0
      x-summary-source: derived
      operationId: postPepuV2Mainnet0
      x-operation-id-source: derived
x-service-info:
  docs:
    llms: /llms.txt
