openapi: 3.1.0
info:
  title: Conduit Nodes Aevo Mainnet Prod 0 Orderly Mainnet 0 API
  version: 1.0.0
tags:
- name: Orderly Mainnet 0
paths:
  /orderly-mainnet-0/:
    post:
      responses:
        '200':
          description: Successful response
      tags:
      - Orderly Mainnet 0
x-service-info:
  docs:
    llms: /llms.txt
