openapi: 3.1.0
info:
  title: Conduit Nodes Aevo Mainnet Prod 0 Lyra Mainnet 0 API
  version: 1.0.0
tags:
- name: Lyra Mainnet 0
paths:
  /lyra-mainnet-0/:
    post:
      responses:
        '200':
          description: Successful response
      tags:
      - Lyra Mainnet 0
x-service-info:
  docs:
    llms: /llms.txt
