openapi: 3.2.0
info:
  title: Conduit Nodes Onyx 6l1k4gho61 API
  version: 1.0.0
tags:
- name: Onyx 6l1k4gho61
paths:
  /onyx-6l1k4gho61/:
    post:
      responses:
        '200':
          description: Successful response
      tags:
      - Onyx 6l1k4gho61
      summary: Create onyx 6l1k4gho61
      x-summary-source: derived
      operationId: postOnyx6l1k4gho61
      x-operation-id-source: derived
x-service-info:
  docs:
    llms: /llms.txt
