openapi: 3.2.0
info:
  title: Conduit Nodes Orderly L2 4460 Sepolia 8tc3sd7dvy API
  version: 1.0.0
tags:
- name: Orderly L2 4460 Sepolia 8tc3sd7dvy
paths:
  /orderly-l2-4460-sepolia-8tc3sd7dvy/:
    post:
      responses:
        '200':
          description: Successful response
      tags:
      - Orderly L2 4460 Sepolia 8tc3sd7dvy
      summary: Create orderly l2 4460 sepolia 8tc3sd7dvy
      x-summary-source: derived
      operationId: postOrderlyL24460Sepolia8tc3sd7dvy
      x-operation-id-source: derived
x-service-info:
  docs:
    llms: /llms.txt
