openapi: 3.2.0
info:
  title: Conduit Nodes Celes 8f2cp9klol API
  version: 1.0.0
tags:
- name: Celes 8f2cp9klol
paths:
  /celes-8f2cp9klol/:
    post:
      responses:
        '200':
          description: Successful response
      tags:
      - Celes 8f2cp9klol
      summary: Create celes 8f2cp9klol
      x-summary-source: derived
      operationId: postCeles8f2cp9klol
      x-operation-id-source: derived
x-service-info:
  docs:
    llms: /llms.txt
