openapi: 3.1.0
info:
  title: Conduit Nodes Aevo Mainnet Prod 0 Kewi Green Svxeewxcc5 API
  version: 1.0.0
tags:
- name: Kewi Green Svxeewxcc5
paths:
  /kewi-green-svxeewxcc5/:
    post:
      responses:
        '200':
          description: Successful response
      tags:
      - Kewi Green Svxeewxcc5
x-service-info:
  docs:
    llms: /llms.txt
