openapi: 3.2.0
info:
  title: Conduit Nodes Mode Mainnet 0 API
  version: 1.0.0
tags:
- name: Mode Mainnet 0
paths:
  /mode-mainnet-0/:
    post:
      responses:
        '200':
          description: Successful response
      tags:
      - Mode Mainnet 0
      summary: Create mode mainnet 0
      x-summary-source: derived
      operationId: postModeMainnet0
      x-operation-id-source: derived
x-service-info:
  docs:
    llms: /llms.txt
