openapi: 3.2.0
info:
  title: Conduit Nodes Varity Testnet Rroe52pwjp API
  version: 1.0.0
tags:
- name: Varity Testnet Rroe52pwjp
paths:
  /varity-testnet-rroe52pwjp/:
    post:
      responses:
        '200':
          description: Successful response
      tags:
      - Varity Testnet Rroe52pwjp
      summary: Create varity testnet rroe52pwjp
      x-summary-source: derived
      operationId: postVarityTestnetRroe52pwjp
      x-operation-id-source: derived
x-service-info:
  docs:
    llms: /llms.txt
