openapi: 3.2.0
info:
  title: Conduit Nodes Stratostack 8h1p47v0ck API
  version: 1.0.0
tags:
- name: Stratostack 8h1p47v0ck
paths:
  /stratostack-8h1p47v0ck/:
    post:
      responses:
        '200':
          description: Successful response
      tags:
      - Stratostack 8h1p47v0ck
      summary: Create stratostack 8h1p47v0ck
      x-summary-source: derived
      operationId: postStratostack8h1p47v0ck
      x-operation-id-source: derived
x-service-info:
  docs:
    llms: /llms.txt
