openapi: 3.1.0
info:
  title: Conduit Nodes Aevo Mainnet Prod 0 Dust Mainnet 0 API
  version: 1.0.0
tags:
- name: Dust Mainnet 0
paths:
  /dust-mainnet-0/:
    post:
      responses:
        '200':
          description: Successful response
      tags:
      - Dust Mainnet 0
x-service-info:
  docs:
    llms: /llms.txt
