openapi: 3.2.0
info:
  title: Conduit Nodes Doma Dev Ix58nm4rnd API
  version: 1.0.0
tags:
- name: Doma Dev Ix58nm4rnd
paths:
  /doma-dev-ix58nm4rnd/:
    post:
      responses:
        '200':
          description: Successful response
      tags:
      - Doma Dev Ix58nm4rnd
      summary: Create doma dev ix58nm4rnd
      x-summary-source: derived
      operationId: postDomaDevIx58nm4rnd
      x-operation-id-source: derived
x-service-info:
  docs:
    llms: /llms.txt
