openapi: 3.1.0
info:
  title: Conduit Nodes Aevo Mainnet Prod 0 Ronin Mainnet Bfz9fadqzl API
  version: 1.0.0
tags:
- name: Ronin Mainnet Bfz9fadqzl
paths:
  /ronin-mainnet-bfz9fadqzl/:
    post:
      responses:
        '200':
          description: Successful response
      tags:
      - Ronin Mainnet Bfz9fadqzl
x-service-info:
  docs:
    llms: /llms.txt
