openapi: 3.2.0
info:
  title: Conduit Nodes Hpp Sepolia Turdrv0107 API
  version: 1.0.0
tags:
- name: Hpp Sepolia Turdrv0107
paths:
  /hpp-sepolia-turdrv0107/:
    post:
      responses:
        '200':
          description: Successful response
      tags:
      - Hpp Sepolia Turdrv0107
      summary: Create hpp sepolia turdrv0107
      x-summary-source: derived
      operationId: postHppSepoliaTurdrv0107
      x-operation-id-source: derived
x-service-info:
  docs:
    llms: /llms.txt
