openapi: 3.1.0
info:
  title: Conduit Nodes Aevo Mainnet Prod 0 Metal Mainnet 0 API
  version: 1.0.0
tags:
- name: Metal Mainnet 0
paths:
  /metal-mainnet-0/:
    post:
      responses:
        '200':
          description: Successful response
      tags:
      - Metal Mainnet 0
x-service-info:
  docs:
    llms: /llms.txt
