openapi: 3.1.0
info:
  title: Conduit Nodes Aevo Mainnet Prod 0 Hpp Sepolia Turdrv0107 API
  version: 1.0.0
tags:
- name: Hpp Sepolia Turdrv0107
paths:
  /hpp-sepolia-turdrv0107/:
    post:
      responses:
        '200':
          description: Successful response
      tags:
      - Hpp Sepolia Turdrv0107
x-service-info:
  docs:
    llms: /llms.txt
