openapi: 3.2.0
info:
  title: Conduit Nodes Stratostack Dpd6y4jwnm API
  version: 1.0.0
tags:
- name: Stratostack Dpd6y4jwnm
paths:
  /stratostack-dpd6y4jwnm/:
    post:
      responses:
        '200':
          description: Successful response
      tags:
      - Stratostack Dpd6y4jwnm
      summary: Create stratostack dpd6y4jwnm
      x-summary-source: derived
      operationId: postStratostackDpd6y4jwnm
      x-operation-id-source: derived
x-service-info:
  docs:
    llms: /llms.txt
