openapi: 3.2.0
info:
  title: Conduit Nodes Cypher Testnet Uvgtmiptr7 API
  version: 1.0.0
tags:
- name: Cypher Testnet Uvgtmiptr7
paths:
  /cypher-testnet-uvgtmiptr7/:
    post:
      responses:
        '200':
          description: Successful response
      tags:
      - Cypher Testnet Uvgtmiptr7
      summary: Create cypher testnet uvgtmiptr7
      x-summary-source: derived
      operationId: postCypherTestnetUvgtmiptr7
      x-operation-id-source: derived
x-service-info:
  docs:
    llms: /llms.txt
