openapi: 3.2.0
info:
  title: Conduit Nodes Kewi Green Svxeewxcc5 API
  version: 1.0.0
tags:
- name: Kewi Green Svxeewxcc5
paths:
  /kewi-green-svxeewxcc5/:
    post:
      responses:
        '200':
          description: Successful response
      tags:
      - Kewi Green Svxeewxcc5
      summary: Create kewi green svxeewxcc5
      x-summary-source: derived
      operationId: postKewiGreenSvxeewxcc5
      x-operation-id-source: derived
x-service-info:
  docs:
    llms: /llms.txt
