openapi: 3.2.0
info:
  title: Conduit Nodes Saigon Testnet Cc58e966ql API
  version: 1.0.0
tags:
- name: Saigon Testnet Cc58e966ql
paths:
  /saigon-testnet-cc58e966ql/:
    post:
      responses:
        '200':
          description: Successful response
      tags:
      - Saigon Testnet Cc58e966ql
      summary: Create saigon testnet cc58e966ql
      x-summary-source: derived
      operationId: postSaigonTestnetCc58e966ql
      x-operation-id-source: derived
x-service-info:
  docs:
    llms: /llms.txt
