openapi: 3.1.0
info:
  title: Conduit Nodes Aevo Mainnet Prod 0 Varity Testnet Rroe52pwjp API
  version: 1.0.0
tags:
- name: Varity Testnet Rroe52pwjp
paths:
  /varity-testnet-rroe52pwjp/:
    post:
      responses:
        '200':
          description: Successful response
      tags:
      - Varity Testnet Rroe52pwjp
x-service-info:
  docs:
    llms: /llms.txt
