openapi: 3.2.0
info:
  title: Conduit Nodes Sepolia Superseed 826s35710w API
  version: 1.0.0
tags:
- name: Sepolia Superseed 826s35710w
paths:
  /sepolia-superseed-826s35710w/:
    post:
      responses:
        '200':
          description: Successful response
      tags:
      - Sepolia Superseed 826s35710w
      summary: Create sepolia superseed 826s35710w
      x-summary-source: derived
      operationId: postSepoliaSuperseed826s35710w
      x-operation-id-source: derived
x-service-info:
  docs:
    llms: /llms.txt
