openapi: 3.1.0
info:
  title: Conduit Nodes Aevo Mainnet Prod 0 Aevo Testnet K1zx5a2ajj API
  version: 1.0.0
tags:
- name: Aevo Testnet K1zx5a2ajj
paths:
  /aevo-testnet-k1zx5a2ajj/:
    post:
      responses:
        '200':
          description: Successful response
      tags:
      - Aevo Testnet K1zx5a2ajj
x-service-info:
  docs:
    llms: /llms.txt
