openapi: 3.2.0
info:
  title: Conduit Nodes Codex Testnet Vmc5bxalmp API
  version: 1.0.0
tags:
- name: Codex Testnet Vmc5bxalmp
paths:
  /codex-testnet-vmc5bxalmp/:
    post:
      responses:
        '200':
          description: Successful response
      tags:
      - Codex Testnet Vmc5bxalmp
      summary: Create codex testnet vmc5bxalmp
      x-summary-source: derived
      operationId: postCodexTestnetVmc5bxalmp
      x-operation-id-source: derived
x-service-info:
  docs:
    llms: /llms.txt
