openapi: 3.1.0
info:
  title: Conduit Nodes Aevo Mainnet Prod 0 Orderly L2 4460 Sepolia 8tc3sd7dvy API
  version: 1.0.0
tags:
- name: Orderly L2 4460 Sepolia 8tc3sd7dvy
paths:
  /orderly-l2-4460-sepolia-8tc3sd7dvy/:
    post:
      responses:
        '200':
          description: Successful response
      tags:
      - Orderly L2 4460 Sepolia 8tc3sd7dvy
x-service-info:
  docs:
    llms: /llms.txt
