openapi: 3.1.0
info:
  title: Conduit Nodes Aevo Mainnet Prod 0 Flynet U82lq6zgmf API
  version: 1.0.0
tags:
- name: Flynet U82lq6zgmf
paths:
  /flynet-u82lq6zgmf/:
    post:
      responses:
        '200':
          description: Successful response
      tags:
      - Flynet U82lq6zgmf
x-service-info:
  docs:
    llms: /llms.txt
