openapi: 3.2.0
info:
  title: Conduit Nodes Forknet API
  version: 1.0.0
tags:
- name: Forknet
paths:
  /forknet/:
    post:
      responses:
        '200':
          description: Successful response
      tags:
      - Forknet
      summary: Create forknet
      x-summary-source: derived
      operationId: postForknet
      x-operation-id-source: derived
x-service-info:
  docs:
    llms: /llms.txt
