openapi: 3.2.0
info:
  title: Conduit Nodes Sheer Tan Crawdad Ggq0xy4dvx API
  version: 1.0.0
tags:
- name: Sheer Tan Crawdad Ggq0xy4dvx
paths:
  /sheer-tan-crawdad-ggq0xy4dvx/:
    post:
      responses:
        '200':
          description: Successful response
      tags:
      - Sheer Tan Crawdad Ggq0xy4dvx
      summary: Create sheer tan crawdad ggq0xy4dvx
      x-summary-source: derived
      operationId: postSheerTanCrawdadGgq0xy4dvx
      x-operation-id-source: derived
x-service-info:
  docs:
    llms: /llms.txt
