openapi: 3.1.0
info:
  title: Conduit Nodes Aevo Mainnet Prod 0 Plume Testnet 1 API
  version: 1.0.0
tags:
- name: Plume Testnet 1
paths:
  /plume-testnet-1/:
    post:
      responses:
        '200':
          description: Successful response
      tags:
      - Plume Testnet 1
x-service-info:
  docs:
    llms: /llms.txt
