openapi: 3.1.0
info:
  title: Conduit Nodes Aevo Mainnet Prod 0 Codex Mainnet 4s9qf7vr0k API
  version: 1.0.0
tags:
- name: Codex Mainnet 4s9qf7vr0k
paths:
  /codex-mainnet-4s9qf7vr0k/:
    post:
      responses:
        '200':
          description: Successful response
      tags:
      - Codex Mainnet 4s9qf7vr0k
x-service-info:
  docs:
    llms: /llms.txt
