openapi: 3.1.0
info:
  title: Conduit Nodes Aevo Mainnet Prod 0 Tempo Moderato API
  version: 1.0.0
tags:
- name: Tempo Moderato
paths:
  /tempo-moderato/:
    post:
      responses:
        '200':
          description: Successful response
      tags:
      - Tempo Moderato
x-service-info:
  docs:
    llms: /llms.txt
